language: julia

os:
 - linux

julia:
 - 1.0
 - 1.1
 - 1.2
 - nightly

matrix:
 allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'if Sys.islinux() && string(VERSION)[1:3] == "1.2"
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    else
      println("Coverage skipped")
    end'
