language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SQP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
